'use client';
import {useState} from 'react';
import {ArrowRight,ChevronDown,Mail,MapPin,Menu,X,Zap,Cpu,Waves,BatteryCharging,Link} from 'lucide-react';
const research=[
{icon:Zap,no:'01',title:'High-density power conversion',text:'Next-generation converters built around wide-bandgap semiconductors, advanced magnetics and intelligent thermal design.'},
{icon:Cpu,no:'02',title:'Integrated power electronics',text:'Bringing switching, sensing, control and packaging closer together for smaller, faster and more reliable systems.'},
{icon:Waves,no:'03',title:'Digital control & intelligence',text:'Real-time control, modelling and data-driven optimisation for resilient, adaptive power conversion.'},
{icon:BatteryCharging,no:'04',title:'Electrification & energy systems',text:'Enabling clean mobility, renewable integration and efficient energy infrastructure from watts to kilowatts.'}];
const news=[['26 JUN 2026','RESEARCH','TPEL launches a new platform for ultra-high-frequency power conversion'],['14 MAY 2026','TEAM','Welcoming new researchers to our power electronics programme'],['03 APR 2026','PUBLICATION','New work on integrated magnetics accepted for IEEE publication']];
export default function Home(){const[open,setOpen]=useState(false);return <main>
<div className="topline">Tyndall National Institute <span>·</span> University College Cork</div>
<header className="site-header"><a className="brand" href="#top"><span className="brand-mark"><i/><i/><i/></span><span><b>TPEL</b><small>Tyndall Power Electronics Laboratory</small></span></a><nav className={open?'nav open':'nav'}>{['Research','People','Projects','Publications','News'].map(x=><a key={x} href={'#'+x.toLowerCase()} onClick={()=>setOpen(false)}>{x}</a>)}<a className="contact-link" href="#contact">Contact <ArrowRight size={16}/></a></nav><button className="menu" onClick={()=>setOpen(!open)} aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button></header>
<section className="hero" id="top"><div className="hero-grid"/><div className="hero-copy"><p className="eyebrow">POWERING WHAT COMES NEXT</p><h1>Smaller.<br/>Smarter. <em>Stronger.</em></h1><p className="lead">We rethink how electrical energy is converted, controlled and integrated — from semiconductor to system.</p><div className="hero-actions"><a className="button primary" href="#research">Explore our research <ArrowRight size={18}/></a><a className="text-link" href="#people">Meet the team <ArrowRight size={16}/></a></div></div><div className="hero-visual"><div className="orb"><div className="pulse p1"/><div className="pulse p2"/><div className="core"><Zap size={42}/></div></div><div className="metric m1"><strong>WBG</strong><span>GaN · SiC</span></div><div className="metric m2"><strong>MHz</strong><span>High frequency</span></div><div className="metric m3"><strong>η</strong><span>Peak efficiency</span></div></div><a className="scroll" href="#intro">SCROLL <ChevronDown size={15}/></a></section>
<section className="intro section" id="intro"><p className="section-kicker">ABOUT TPEL</p><div className="intro-layout"><h2>Power electronics,<br/><span>reimagined in Cork.</span></h2><div><p className="intro-text">Led by Senior Researcher <strong>Dr Yi Dou</strong>, TPEL is a new power electronics research group at Tyndall National Institute. We connect world-class microelectronics capability with system-level thinking to solve hard problems in sustainable energy and electrification.</p><a className="arrow-link" href="#people">Discover our laboratory <ArrowRight size={18}/></a></div></div><div className="stats"><div><b>4</b><span>Research pillars</span></div><div><b>1</b><span>Shared mission</span></div><div><b>∞</b><span>Possibilities</span></div></div></section>
<section className="research section" id="research"><div className="section-head"><div><p className="section-kicker light">OUR RESEARCH</p><h2>From device to grid.</h2></div><p>We work across the full power-conversion stack, translating deep science into technology that matters.</p></div><div className="research-grid">{research.map(({icon:Icon,...r})=><article className="research-card" key={r.no}><span className="card-number">{r.no}</span><Icon className="card-icon"/><h3>{r.title}</h3><p>{r.text}</p><a href="#projects"><ArrowRight/></a></article>)}</div></section>
<section className="leader section" id="people"><div className="portrait"><div className="portrait-label"><span>LAB LEAD</span><b>Dr Yi Dou</b></div></div><div className="leader-copy"><p className="section-kicker">PEOPLE</p><h2>Curiosity is<br/>our current.</h2><p>Our group brings together researchers in power conversion, semiconductor devices, packaging, controls and energy systems. We believe the best breakthroughs happen when disciplines — and people — connect.</p><blockquote>“We build power electronics that make ambitious systems possible.”</blockquote><p className="role"><strong>Dr Yi Dou</strong><br/>Senior Researcher · Group Lead</p><div className="socials"><a href="mailto:yi.dou@tyndall.ie"><Mail size={18}/></a><a href="https://www.tyndall.ie/"><Link size={18}/></a></div></div></section>
<section className="projects section" id="projects"><div className="section-head dark"><div><p className="section-kicker">SELECTED WORK</p><h2>Engineering impact.</h2></div><a className="arrow-link" href="#publications">View publications <ArrowRight size={18}/></a></div>{[['01','GaN · Power density','Ultra-compact converters for future data infrastructure'],['02','SiC · E-mobility','High-efficiency power modules for electrified transport'],['03','Magnetics · Integration','Planar magnetics for next-generation power supplies']].map(p=><div className="project-row" key={p[0]}><div className="project-index">{p[0]}</div><div className="project-tags">{p[1]}</div><h3>{p[2]}</h3><ArrowRight/></div>)}</section>
<section className="news section" id="news"><div className="news-title"><p className="section-kicker">LATEST</p><h2>News &<br/>perspectives.</h2></div><div className="news-list">{news.map(n=><article key={n[0]}><div><time>{n[0]}</time><span>{n[1]}</span></div><h3>{n[2]}</h3><ArrowRight/></article>)}</div></section>
<section className="join" id="contact"><div><p className="section-kicker light">WORK WITH US</p><h2>Let’s move energy<br/>forward.</h2></div><div><p>We welcome ambitious researchers, students and industry partners who want to shape the future of power electronics.</p><a className="button pale" href="mailto:yi.dou@tyndall.ie">Start a conversation <ArrowRight size={18}/></a></div></section>
<footer><div className="footer-brand"><span className="brand-mark"><i/><i/><i/></span><b>TPEL</b><p>Tyndall Power Electronics Laboratory</p></div><div><h4>Navigate</h4><a href="#research">Research</a><a href="#people">People</a><a href="#projects">Projects</a><a href="#news">News</a></div><div><h4>Visit</h4><p><MapPin size={15}/> Lee Maltings<br/>Dyke Parade<br/>Cork, Ireland</p></div><div><h4>Connect</h4><a href="mailto:yi.dou@tyndall.ie">yi.dou@tyndall.ie</a><a href="https://www.tyndall.ie/">tyndall.ie ↗</a></div><div className="copyright">© 2026 Tyndall Power Electronics Laboratory <span>Privacy · Accessibility</span></div></footer>
</main>}
