import {openings} from './opportunities.mjs';
import {publications} from './publications.mjs';
import {teamMembers} from './team-members.mjs';
import news from './news.json' with {type:'json'};
export function siteContent(base=''){
const nav=[['Home',''],['Research','research'],['People','people'],['News','news'],['Publications','publications'],['Opportunities','opportunities']];
const header=`<div class="institution"><a href="https://www.tyndall.ie/">Tyndall National Institute</a></div><header><a class="wordmark" href="${base}/"><span>Integrated Power Electronics Team</span></a><nav>${nav.map(([n,p])=>`<a href="${base}/${p}${p?'/':''}">${n}</a>`).join('')}</nav></header>`;
const footer=`<footer><div><b>Integrated Power Electronics Team</b><p>Integrated Power and Energy Systems Research Programme</p><p class="institution-address">Tyndall National Institute<br>Lee Maltings, Dyke Parade<br>Cork, Ireland<br>T12 R5CP</p></div><div><b>Contact</b><p>Yi Dou<br>Senior Researcher, Ph.D</p><a href="mailto:yi.dou@tyndall.ie">yi.dou@tyndall.ie</a></div><div><b>Institution</b><a href="https://www.tyndall.ie/">Tyndall National Institute</a><a href="https://www.ucc.ie/">University College Cork</a></div><div class="brand-signoff"><a class="brand-primary" href="https://www.tyndall.ie/" aria-label="Tyndall National Institute"><img src="${base}/brands/tyndall-logo.png" alt="Tyndall"></a><div class="founding-partners"><span>Founding partners</span><div><a href="https://www.gov.ie/" aria-label="Government of Ireland"><img src="${base}/brands/government-of-ireland.svg" alt="Government of Ireland"></a><a href="https://www.ucc.ie/" aria-label="University College Cork"><img src="${base}/brands/ucc-logo.png" alt="UCC – University College Cork"></a></div></div></div><small>© 2026 Integrated Power Electronics Team</small></footer>`;
const pages={
'':`<div class="cover" role="img" aria-label="Tyndall National Institute, Cork"></div><article class="home-copy"><h1>Integrated Power Electronics Team</h1><p>We advance integrated power electronic systems from semiconductor devices and passive components to packaging, modelling and application-led system design.</p><p>Our aim is direct: zero-loss, zero-volume power electronics. We create knowledge, develop researchers and translate technologies towards industrial use.</p></article><div class="home-links"><section><h2>Research</h2><a href="${base}/research/">Research Thrusts</a><a href="${base}/publications/">Publications</a></section><section><h2>Team</h2><a href="${base}/people/">People</a><a href="${base}/opportunities/">Open opportunities</a></section></div>`,
research:`<div class="content"><div class="page-title"><h1>Research</h1><p class="research-vision">Research Vision - Towards Zero-Loss Zero-Volume Power Management Systems</p></div><h2>Research thrusts</h2><div class="indexed">${[['Advanced devices & components','WBG and UWBG power-switch characterisation, advanced control and PMIC optimisation, novel magnetics and advanced capacitors.'],['Advanced system integration','Low-parasitic packaging, electro-thermal design, thermal management and co-integration of devices, passives and cooling structures.'],['Advanced modelling & design','Physics-based, mathematical and data-driven modelling, multi-objective optimisation and virtual prototyping.']].map((a,i)=>`<section><span>0${i+1}</span><div><h3>${a[0]}</h3><p>${a[1]}</p></div></section>`).join('')}</div><h2>Application roadmap</h2><div class="application-list">${[['AI data-centre power delivery','High-current, fast-transient voltage regulation from rack-level conversion to processor point-of-load.'],['Co-packaged silicon photonics','Compact, low-noise power conversion integrated alongside electronic and photonic chiplets.'],['Edge AI hardware','Miniaturised, energy-efficient power management for distributed sensing and computing.'],['Aerospace electrical systems','Lightweight, high-density and high-reliability conversion for harsh operating environments.'],['Biomedical electronics','Miniaturised, low-noise and safe power delivery for wearable and implantable systems.'],['Industrial electrification','High-efficiency conversion and integrated power modules for automation and distributed energy systems.']].map(a=>`<p><strong>${a[0]}</strong><span>${a[1]}</span></p>`).join('')}</div><h2>Research projects</h2><div class="project-list"><article><h3><a href="https://www.tyndall.ie/projects/fames-pilot-line-2/">FAMES Pilot Line</a></h3><p>Integrated magnetics, high-density capacitors and PMIC integration for advanced FD-SOI and 3D power delivery.</p></article><article><h3><a href="https://www.tyndall.ie/rinn-semiconductors/">Rinn Semiconductors</a></h3><p>Heterogeneous integration, chiplet architectures and advanced packaging from materials to system-level applications.</p></article></div></div>`,
people:`<div class="content"><div class="page-title"><h1>People</h1></div><div class="person"><img class="person-photo yi-portrait" src="${base}/people/yi-dou-portrait-v2.jpeg" alt="Yi Dou"><div><h2>Yi Dou</h2><p class="meta">Senior Researcher/Scientist, PhD at DTU</p><p><strong>Research focus</strong></p><p>Integrated power electronics, high-frequency conversion, advanced magnetics and power-supply-on-chip systems.</p><a href="mailto:yi.dou@tyndall.ie">yi.dou@tyndall.ie</a><a href="https://research.ucc.ie/en/persons/yi-dou/">UCC profile</a></div></div><h2>Team members</h2><div class="member-list">${teamMembers.map(m=>`<article class="member-row"><h3><a href="${base}/people/${m.slug}/">${m.name}</a></h3><p class="member-role">${m.role}</p>${m.focus?`<div class="member-focus"><p class="focus-label">Research focus</p><p>${m.focus}</p></div>`:''}<a class="member-linkedin" href="${m.linkedin}">LinkedIn</a></article>`).join('')}</div><h2>Director of Integrated Power and Energy Systems Research Programme</h2><div class="person"><img class="person-photo" src="${base}/people/cian-omathuna.jpg" alt="Professor Cian Ó Mathúna"><div><h2 id="cian-omathuna">Professor Cian Ó Mathúna</h2><p class="meta">IEEE Fellow</p><p><strong>Research focus</strong></p><p>Integrated power systems, magnetics-on-silicon, power supply on chip and technology translation.</p><a href="https://www.tyndall.ie/people/cian-omathuna/">Tyndall profile</a></div></div></div>`,
publications:`<div class="content"><div class="page-title"><h1>Publications</h1></div><p>Publications with Tyndall National Institute affiliation.</p><nav class="year-menu" aria-label="Publication years">${[...new Set(publications.map(p=>p.year))].sort((a,b)=>b-a).map(year=>`<a href="#year-${year}">${year}</a>`).join('')}</nav>${[...new Set(publications.map(p=>p.year))].sort((a,b)=>b-a).map(year=>`<section class="publication-year" id="year-${year}"><h2>${year}</h2><div class="publication-list">${publications.filter(p=>p.year===year).map((p,i)=>`<article><span>${String(i+1).padStart(2,'0')}</span><div><h3><a href="${p.url}">${p.title}</a></h3><p class="publication-authors">${p.authors.map(name=>{const member=teamMembers.find(m=>m.name===name || (name==='Raúl Henares' && m.slug==='raul-henares-vargas'));const path=name==='Yi Dou'?'people/':name==='Cian Ó Mathúna'?'people/#cian-omathuna':member?'people/'+member.slug+'/':null;return path?`<a href="${base}/${path}">${name}</a>`:name;}).join(', ')}</p><p class="publication-venue">${p.venue}, pp. ${p.pages}.</p></div></article>`).join('')}</div></section>`).join('')}<p>For earlier publications, please visit Yi Dou's Google Scholar profile.</p><a class="document-link" href="https://scholar.google.com/citations?user=LrU0d14AAAAJ&hl=en&oi=ao">Yi Dou on Google Scholar</a></div>`,
opportunities:`<div class="content"><div class="page-title"><h1>Opportunities</h1></div><h2>Currently available positions</h2><ul class="openings-list">${openings.map(o=>`<li><span class="opening-count">${o.count}</span><span>${o.label}</span></li>`).join('')}</ul><p>Enquiries are welcome.</p><h2>Research enquiries</h2><p>Prospective students and researchers interested in power electronics may contact Yi Dou with a curriculum vitae and a short description of their research interests.</p><a class="document-link" href="mailto:yi.dou@tyndall.ie">Contact Yi Dou</a></div>`,};

pages.news = '<div class="content"><div class="page-title"><h1>News</h1><p>Team activities and research updates.</p></div><div class="news-list">'+news.map(item=>`<article><p class="meta">${item.date}</p><h2>${item.title}</h2><p>${item.body}</p><a href="${item.source}">${item.sourceLabel || 'Read on LinkedIn'}</a></article>`).join('')+'</div></div>';

for(const m of teamMembers){
 pages['people/'+m.slug]=`<article class="content member-profile"><a class="back-link" href="${base}/people/">Back to People</a><div class="page-title"><h1>${m.name}</h1><p>${m.role}</p></div><div class="profile-body"><img class="profile-portrait" src="${base}/people/${m.slug}.png" alt="${m.name}" width="200" height="200"><div>${m.focus?`<h2>Research focus</h2><p>${m.focus}</p>`:''}${m.biography?`<h2>About</h2><p>${m.biography}</p>`:''}${m.experience?`<h2>Experience</h2><p>${m.experience}</p>`:''}${m.education?`<h2>Education</h2><p>${m.education}</p>`:''}<div class="profile-links"><a href="${m.linkedin}">LinkedIn</a>${m.source?`<a href="${m.source}">${m.sourceLabel}</a>`:''}</div></div></div></article>`;
}
return {header,footer,pages,nav};
}
